"""
generate_newsletter.py - 한글/영어 뉴스레터 동시 생성
Usage: python scripts/generate_newsletter.py
"""
import json, sys, os, subprocess
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.getcwd())

def run_quant(cmd):
    result = subprocess.run(
        ["python", "scripts/quant.py", *cmd.split()],
        capture_output=True, text=True,
        env={**os.environ, "PYTHONPATH": os.getcwd(), "PYTHONIOENCODING": "utf-8"}
    )
    return json.loads(result.stdout)

def generate(date_str, momentum, factor, season):
    top5_mom = momentum["rankings"][:5]
    top5_fac = factor["rankings"][:5]
    s = season["season_info"]
    all_neg = all(r["score"] < 0 for r in momentum["rankings"])
    signal_kr = "⚠️ 현금 유지" if all_neg else "🟢 매수 검토"
    signal_en = "HOLD CASH" if all_neg else "CONSIDER BUY"
    top_coin = top5_mom[0]["symbol"].replace("KRW-", "")

    # --- 한글 ---
    rows_kr = "\n".join(
        f"| {'🥇🥈🥉'[i] if i < 3 else str(i+1)} | **{r['symbol'].replace('KRW-','')}** | {r['score']:.3f} |"
        for i, r in enumerate(top5_mom)
    )
    fac_rows_kr = "\n".join(
        f"| {i+1} | **{r['symbol'].replace('KRW-','')}** | {r['composite_score']:.3f} |"
        for i, r in enumerate(top5_fac)
    )
    kr = f"""---
title: "AI 퀀트 레터 — {date_str}"
date: {date_str}
tags: [퀀트, 암호화폐, 업비트, AI투자, maiupbit]
language: ko
---

# 🤖 AI 퀀트 레터 — {date_str}
**업비트 주간 퀀트 시그널 | [maiupbit](https://pypi.org/project/maiupbit/) 자동 생성**

## 📅 시장 시즌
| 항목 | 현황 |
|------|------|
| 시즌 | {'🟢 강세장' if s['season']=='bullish' else '🔴 약세장'} ({s['month']}월) |
| 할빙 사이클 | {s['halving_phase']} (할빙 후 {s['days_since_halving']}일) |
| 가중치 | {s['multiplier']}× |

## 🏆 이중 모멘텀 TOP 5
| 순위 | 코인 | 점수 |
|------|------|------|
{rows_kr}

> **매매 시그널: {signal_kr}**

## 📊 멀티팩터 TOP 5
| 순위 | 코인 | 점수 |
|------|------|------|
{fac_rows_kr}

---
*⚠️ 투자 정보 제공 목적, 투자 권유 아님*
*소스코드: https://github.com/jini92/M.AI.UPbit*
"""

    # --- 영어 ---
    rows_en = "\n".join(
        f"| {'🥇🥈🥉'[i] if i < 3 else str(i+1)} | **{r['symbol'].replace('KRW-','')}** | {r['score']:.3f} |"
        for i, r in enumerate(top5_mom)
    )
    fac_rows_en = "\n".join(
        f"| {i+1} | **{r['symbol'].replace('KRW-','')}** | {r['composite_score']:.3f} |"
        for i, r in enumerate(top5_fac)
    )
    en = f"""---
title: "AI Quant Letter — {date_str}"
date: {date_str}
tags: [quant, crypto, upbit, ai-trading, maiupbit, python]
language: en
---

# 🤖 AI Quant Letter — {date_str}
**Weekly UPbit Crypto Signals | Auto-generated by [maiupbit](https://pypi.org/project/maiupbit/)**

## 📅 Market Season
| Metric | Status |
|--------|--------|
| Season | {'🟢 Bullish' if s['season']=='bullish' else '🔴 Bearish'} (Month {s['month']}) |
| Halving Cycle | {s['halving_phase']} (Day {s['days_since_halving']} post-halving) |
| Multiplier | {s['multiplier']}× |

## 🏆 Dual Momentum TOP 5
| Rank | Coin | Score |
|------|------|-------|
{rows_en}

> **Signal: {signal_en}**

## 📊 Multi-Factor TOP 5
| Rank | Coin | Score |
|------|------|-------|
{fac_rows_en}

---
*⚠️ For informational purposes only, not investment advice*
*Open source (Apache 2.0): https://github.com/jini92/M.AI.UPbit*
"""
    return kr, en

if __name__ == "__main__":
    date_str = datetime.now().strftime("%Y-%m-%d")
    print("📊 Fetching quant data...")
    momentum = run_quant("momentum --top 5")
    factor   = run_quant("factor --top 5")
    season   = run_quant("season")

    kr, en = generate(date_str, momentum, factor, season)

    draft_dir = Path("blog/drafts")
    draft_dir.mkdir(parents=True, exist_ok=True)

    kr_path = draft_dir / f"{date_str}_Newsletter_KR.md"
    en_path = draft_dir / f"{date_str}_Newsletter_EN.md"
    kr_path.write_text(kr, encoding="utf-8")
    en_path.write_text(en, encoding="utf-8")

    print(f"✅ KR: {kr_path}")
    print(f"✅ EN: {en_path}")
