"""
Publish weekly quant newsletter to Substack.
Auto-generates content from maiupbit quant engine and posts via Substack API.
"""

import os
import sys
import json
import datetime
import requests
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

SUBSTACK_URL = "https://jinilee.substack.com"
SUBSTACK_SID = os.environ.get("SUBSTACK_SID", "")


def get_quant_data():
    """Run quant analysis and return results."""
    from dotenv import load_dotenv
    load_dotenv()

    try:
        from maiupbit.strategies.dual_momentum import DualMomentumStrategy
        from maiupbit.strategies.multi_factor import MultiFactorStrategy
        from maiupbit.analysis.seasonal import SeasonalAnalyzer

        symbols = ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-SOL",
                   "KRW-DOT", "KRW-AVAX", "KRW-LINK", "KRW-ADA", "KRW-DOGE"]

        # Dual momentum
        dm = DualMomentumStrategy()
        dm_results = dm.rank(symbols)

        # Multi factor
        mf = MultiFactorStrategy()
        mf_results = mf.rank(symbols)

        # Seasonal
        sa = SeasonalAnalyzer()
        season = sa.get_current_season()

        return {"dual_momentum": dm_results, "multi_factor": mf_results, "season": season}
    except Exception as e:
        print(f"Warning: Could not run live quant data: {e}", file=sys.stderr)
        return None


def build_html(data, week_num: int, date_str: str) -> str:
    """Build HTML content for Substack post."""
    if data:
        dm = data.get("dual_momentum", [])
        mf = data.get("multi_factor", [])
        season = data.get("season", {})
        season_emoji = "🟢" if season.get("season") == "bullish" else "🔴"
        season_label = season.get("season", "N/A").capitalize()
        multiplier = season.get("multiplier", 1.0)

        # Check if any coin has positive momentum
        positive = [r for r in dm if r.get("score", -1) > 0]
        signal = "🟢 ENTER" if positive else "⚠️ HOLD CASH"

        dm_rows = "".join([
            f"<tr><td>{i+1}</td><td><b>{r['symbol'].replace('KRW-','')}</b></td>"
            f"<td>{r.get('score',0):.3f}</td></tr>"
            for i, r in enumerate(dm[:5])
        ])
        mf_rows = "".join([
            f"<tr><td>{i+1}</td><td><b>{r['symbol'].replace('KRW-','')}</b></td>"
            f"<td>{r.get('score',0):.3f}</td></tr>"
            for i, r in enumerate(mf[:5])
        ])
    else:
        season_emoji, season_label, multiplier = "🟢", "Bullish", 1.2
        signal = "⚠️ HOLD CASH — all coins negative momentum"
        dm_rows = "<tr><td colspan='3'>Data unavailable</td></tr>"
        mf_rows = "<tr><td colspan='3'>Data unavailable</td></tr>"

    html = f"""
<p><em>Auto-generated by <a href="https://github.com/jini92/M.AI.UPbit">maiupbit</a>,
an open-source quant engine for Korean crypto exchanges (Apache 2.0).</em></p>

<hr/>

<h2>📅 Market Season — {date_str}</h2>
<table>
<tr><th>Metric</th><th>Status</th></tr>
<tr><td>Season</td><td>{season_emoji} <b>{season_label}</b></td></tr>
<tr><td>Multiplier</td><td><b>{multiplier}×</b></td></tr>
</table>

<h2>🏆 Dual Momentum TOP 5</h2>
<p><em>Based on Antonacci's dual momentum adapted for UPbit</em></p>
<table>
<tr><th>Rank</th><th>Coin</th><th>Score</th></tr>
{dm_rows}
</table>
<p><b>Weekly Signal: {signal}</b></p>

<h2>📊 Multi-Factor TOP 5</h2>
<table>
<tr><th>Rank</th><th>Coin</th><th>Score</th></tr>
{mf_rows}
</table>

<hr/>

<h2>🔧 How This Works</h2>
<p>This newsletter is auto-generated by
<a href="https://github.com/jini92/M.AI.UPbit">maiupbit</a>,
implementing 6 quantitative strategies: Dual Momentum, Volatility Breakout,
Multi-Factor Ranking, GTAA Asset Allocation, Seasonal Filter, Risk Management.</p>

<pre><code>pip install maiupbit
maiupbit recommend --top 5</code></pre>

<p><em>⚠️ For informational purposes only. Not financial advice.</em></p>
"""
    return html


def publish_post(title: str, html: str, subtitle: str = "") -> dict:
    """Publish post to Substack via API."""
    if not SUBSTACK_SID:
        raise ValueError("SUBSTACK_SID environment variable not set")

    session = requests.Session()
    session.cookies.set("substack.sid", SUBSTACK_SID, domain="jinilee.substack.com")
    session.headers.update({"Content-Type": "application/json"})

    payload = {
        "type": "newsletter",
        "draft": False,
        "title": title,
        "subtitle": subtitle,
        "body_html": html,
        "audience": "everyone",
    }

    resp = session.post(f"{SUBSTACK_URL}/api/v1/posts", json=payload)
    resp.raise_for_status()
    return resp.json()


def main():
    today = datetime.date.today()
    week_num = today.isocalendar()[1]
    date_str = today.strftime("%Y-%m-%d")

    title = f"AI Quant Letter #{week_num} — Weekly UPbit Signals ({date_str})"
    subtitle = "Dual Momentum + Multi-Factor Rankings powered by maiupbit (Apache 2.0)"

    print(f"Generating quant data for {date_str}...")
    data = get_quant_data()

    print("Building newsletter HTML...")
    html = build_html(data, week_num, date_str)

    print(f"Publishing: {title}")
    result = publish_post(title, html, subtitle)

    post_url = f"{SUBSTACK_URL}/p/{result.get('slug', '')}"
    print(f"✅ Published! URL: {post_url}")
    print(json.dumps({"post_id": result.get("id"), "url": post_url, "title": title}))


if __name__ == "__main__":
    main()
